### ISSUE TITLE
Markdown error in documentation

### ISSUE THREAD

**Issue by edent** [alphagov/pay-tech-docs#39]
![screen shot 2017-09-18 at 11 12 39](https://user-images.githubusercontent.com/837136/30537634-5a9f5e10-9c62-11e7-80f2-6f49dc2e2b89.png)

Looks like a missing space on https://github.com/alphagov/pay-tech-docs/blob/master/source/documentation/03-before-you-start.md

**Comment by NeilBookless** [comment]
I think the '>' should be a Carriage Return (New paragraph).

Also, the explanation is passive: "it took ...".  If it does not make any
difference how many developers are involved, then it may be better to
phrase this as: "...capability. Please allow 5 working days to integrate
your service with GOV.UK Pay."

Best regards
Neil

NB:  Not to my taste, but we should write the numbers 2 onward as
numerals...

-- 


*Neil Bookless *

Technical Author, GOV.UK Verify


GOV.UK Verify <https://identityassurance.blog.gov.uk/> | @GOVUKverify
<https://twitter.com/GOVUKverify>

The White Chapel Building | 10 Whitechapel High Street | London | E1 8QS
M: +44 (0) 7748 377 970
